// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsE_C9j4ImnVfnqQiJmT2zCC07cFv6fuI',
    appId: '1:482449647759:web:67026a56fe51f104b6a8fa',
    messagingSenderId: '482449647759',
    projectId: 'flutter-riverpod-with-firebase',
    authDomain: 'flutter-riverpod-with-firebase.firebaseapp.com',
    storageBucket: 'flutter-riverpod-with-firebase.appspot.com',
    measurementId: 'G-RYQK2RZ3T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBfpMkCpW9Qn82cjye7BF6Zgtr8bhh8Q',
    appId: '1:482449647759:android:a9418ebf5e24b753b6a8fa',
    messagingSenderId: '482449647759',
    projectId: 'flutter-riverpod-with-firebase',
    storageBucket: 'flutter-riverpod-with-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDND5RP1xj096tHnVEidaWXoRrfC3IoiNg',
    appId: '1:482449647759:ios:12184296d17272ceb6a8fa',
    messagingSenderId: '482449647759',
    projectId: 'flutter-riverpod-with-firebase',
    storageBucket: 'flutter-riverpod-with-firebase.appspot.com',
    iosBundleId: 'com.riverpodfirebase.app.dev',
  );
}
